### PR TITLE
add 2024 CEPLAS and Mibinet events

### PR DESCRIPTION
**Pull request by Brilator**
Not ideal, since multi-day series are repetitive. 
But otherwise they would be displayed as single events only.

### CODE REVIEW

**Comment by Brilator** [comment]
@Freymaurer

**Comment by kMutagene** [comment]
@Brilator does this fit into the new layout that was merged?

**Comment by Brilator** [comment]
No. Those were meant for fornax-based site.

**Comment by Brilator** [comment]
I PRed for the time until astro launch. So, if that's around the corner, I'm ready to recreate.

**Comment by kMutagene** [comment]
We'll hopefully launch today!

**Pull request closed without merging**
