### PR TITLE
add event bianca

### PR DESCRIPTION
**Pull request by Brilator**
Hi Bianca, the event issue template is not completely up-to-date with the website development. 

You might want to add more information. Have a look at some of the other events at https://nfdi4plants.github.io/events/

#199 

@blaker42

### CODE REVIEW

**Comment by blaker42** [comment]
Hi Dominik,
I already wondered about the template. I added a description for the event like most events have. It should be fine now. Thanks!

**Comment by Brilator** [comment]
Can you do me a favor and take over the PR?

**Comment by blaker42** [comment]
I can not do a pull request (PR)? I only find the information here 'Only those with write access to this repository can merge pull requests.'

**Comment by Freymaurer** [comment]
What is the state of this PR? It is not described as draft, but seems unfinished?

**Comment by Brilator** [comment]
I've updated to latest event schema with a few missing values. 
Please merge, so @blaker42 can take over from main. Thanks

**Pull request merged**
